options - content appearance
bodyClass: aString
  "body_class

This option enables you to specify a class for the body of each editor instance. This class can then be used to do TinyMCE specific overrides in your content_css. There is also a specific mceForceColors class that can be used to override the text and background colors to be black and white.

Type: String"

  self optionAt: 'body_class' put: aString