options - editor appearance
insertButtonItems: aString
  "insert_button_items

This enables you to specify what to display in the insert buttons menu. The value of this option should be a space separated list of menu item control identifiers or | for a menu separator.

Type: String

Defaults: Defaults to anything marked with the 'insert' context"

  self optionAt: 'inset_button_items' put: aString