options - editor appearance
insertToolbar: aString
  "insert_toolbar

This enables you to specify toolbar items to include in the inlite themes insert toolbar. We recommend that you only have insert related controls in this toolbar but nothing is restricting you to use any of the available toolbar controls.

Type: String

Defaults: quickimage quicktable"

  self optionAt: 'insert_toolbar' put: aString