options - integration and setup
selector: aString
  "selector

This option allows you to specify a CSS selector for the areas that TinyMCE should make editable.

When using this option in TinyMCE's regular editing mode, the element will be replaced with an iframe that TinyMCE will perform all operations within.

Replace all textarea elements on the page

Type: String"

  self optionAt: 'selector' put: aString