options - editor appearance
selectionToolbar: aString
  "selection_toolbar

The enables you to specify toolbar items to include in the inlite themes text selection toolbar. We recommend that you only have formatting related controls in this toolbar but nothing is restricting you to use any of the available toolbar controls.

Type: String

Defaults: bold italic | quicklink h2 h3 blockquote"

  self optionAt: 'selection_toolbar' put: aString