options - content formatting
styleFormats: anArray
  "style_formats

This option enables you to add more advanced style formats for text and other elements to the editor. The value of this option will be rendered as styles in the Formats dropdown.

The format of the option is very similar to the formats option, the only difference is the title name that is used for presentation in the drop list.

Type: Array

https://www.tinymce.com/docs/configure/content-formatting/#style_formats"

  self optionAt: 'style_formats' put: anArray