options - content filtering
validClasses: aStringOrDictionary
  "valid_classes

This option enables you to restrict the classes that are valid for specific elements. This option takes two formats: one string format that is a simple list of allowed global classes, and a more complex object format where you can specify classes for individual elements.

Type: String, Object"

  self optionAt: 'valid_classes' put: aStringOrDictionary